# Generated by Django 4.0.4 on 2022-05-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudForm',
            fields=[
                ('sname', models.CharField(max_length=35, null=True)),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('gen', models.CharField(max_length=35, null=True)),
                ('state', models.CharField(max_length=10, null=True)),
                ('mail', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=35, null=True)),
                ('level', models.CharField(max_length=1, null=True)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
