# Generated by Django 4.0.4 on 2022-05-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studform',
            name='department',
            field=models.CharField(choices=[('none', 'none'), ('IT', 'information technology'), ('CS', 'computer science'), ('AI', 'aitificial intelegence'), ('IS', 'information systems'), ('DS', 'decision support')], default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studform',
            name='level',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studform',
            name='mail',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
