# Generated by Django 4.0.4 on 2022-05-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_studform_department_alter_studform_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studform',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
