# Generated by Django 4.0.4 on 2022-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_studform_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studform',
            name='department',
            field=models.CharField(choices=[('General', 'General'), ('Information System', 'Information System'), ('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Artificial Inteligence', 'Artificial Inteligence')], max_length=50, null=True),
        ),
    ]
